# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'github-metrics.svg'
      - 'README.md'

jobs:
  github-metrics:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: APPARENT1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Etc/GMT-8
